{
    "num_minima" : 3,
    "minima" : [[-0.7, 1.5],
                [0.0, 0.5],
                [0.5, 0.0]],
    "minima_step_factor" : 0.0001,
    "minima_num_steps" : 10000,
    "path_samples" : 50,
    "path_step_factor" : 0.000001,
    "path_num_steps" : 20000
}