initial_point : [1.133, -1.486]
final_point : [-1.166, 1.477]
potential : wolfe_schlegel
path : mlp
path_config : test
loss_functions :
    e_vre : [1., {}]
optimizer : adam
optimizer_params :
    learning_rate : 0.001