initial_point : [1.133, -1.486]
final_point : [-1.166, 1.477]
potential : wolfe_schlegel
path : mlp
path_config_tag : small
integral_params :
    method : dopri5
    rtol : 1e-5
    atol : 1e-5
    computation : parallel
    sample_type : uniform
loss_function : E_pvre
optimizer : adam
optimizer_config_tag : test
optimizer_params :
    lr : 0.001
