initial_point : [420.9687, 420.9687]
final_point : [203.8142, 203.8142]
# final_point : [-302.5249, -302.5249]
potential : schwefel
potential_params :
    dim: 2
path : mlp
path_config_tag : small
integral_params :
  solver: euler
  computation: parallel
  # solver: dopri5
  # computation: serial
  rtol: 1e-3
  atol: 1e-3
  device: cuda
loss_function : E_pvre
optimizer : adam
optimizer_config_tag : test
optimizer_params :
    lr : 0.001