init_params:
  images: configs/6445.xyz
  path_params: 
    name: mlp
    n_embed: 1
    depth: 2
    activation: gelu
  num_record_points: 101
  output_dir: output
  device: cuda
  seed: 0
opt_params:  
  - potential_params:
      potential: repel
    integrator_params: 
      path_ode_names: geodesic
    optimizer_params:
      optimizer:
        name: adam
        lr: 1.0e-3
      lr_scheduler:
        name: cosine
        T_max: 1000
    num_optimizer_iterations: 1000
  - potential_params:
      potential: newtonnet
      model_path: t1x
    integrator_params: 
      path_ode_names: projected_variable_reaction_energy
    optimizer_params:
      optimizer:
        name: adam
        lr: 1.0e-3
      lr_scheduler:
        name: cosine
        T_max: 1000
    num_optimizer_iterations: 1000
