images: configs/acetaldehyde.xyz
potential_params:
  potential: newtonnet
  model_path: configs/newtonnet/training_52/models/best_model_state.tar
  settings_path: configs/newtonnet/training_52/run_scripts/config0.yml
  hess_method: null
path_params: 
  name: mlp_dist
  n_embed : 32
  depth : 3
integrator_params: 
  method : dopri5
  rtol : 1.0e-4
  atol : 1.0e-6
  computation : parallel
  sample_type : uniform
optimizer_params: 
  name: adam
  loss_name: E_pvre_vre
  lr : 1.0e-2
loss_scheduler_params:
  vre_scale:
    value: 1.0
    name: cosine
    start_factor: 0.0
    end_factor: 1.0
    total_iters: 1001
  pvre_scale:
    value: 1.0
    name: cosine
    start_factor: 1.0
    end_factor: 0.0
    total_iters: 1001
num_optimizer_iterations: 1001
output_dir: output