initialization_params:
  images: configs/lj13.xyz
  path_params:
    name: mlp
    width: 128
    depth: 2
    activation: gelu
  track_loss: true
  track_ts: true
  num_record_points: 101
  device: cuda
  dtype: float32
  seed: 0
optimization_params:
  - potential_params:
      name: lennard_jones
    integrator_params:
      path_integrand_names: pvre
      rtol: 1.0
    optimizer_params:
      optimizer:
        name: adam
        lr: 0.01
      threshold: 0.1
    num_optimizer_iterations: 1000
