# images: 6961_interp.xyz
# images: 4766_interp.xyz
# images: 6445_interp.xyz
# images: 6445.xyz
images: 7780_interp.xyz
potential_params:
  potential: newtonnet
  model_path: newtonnet/training_14/models/best_model.pt
  # potential: morse
path_params: 
  name: mlp
  # n_embed: 256
  n_embed: 16
  depth: 3
  activation: gelu
integrator_params: 
  method: dopri5
  rtol: 1.0e-3
  atol: 1.0e-5
  computation: parallel
  sample_type: uniform
  path_loss_name: integral
  # path_loss_name: growing_string
  # path_loss_params:
  #     weight_type: inv_gauss
  path_ode_names: E_pvre
optimizer_params:
  optimizer:
    name: adam
    lr: 1.0e-2
  lr_scheduler:
    # name: cosine
    # T_max: 1000
    name: one_cycle
    max_lr: 1.0e-2
    total_steps: 1000
    # cycle_momentum: false
    # name: cyclic
    # base_lr: 1.0e-3
    # max_lr: 1.0e-2
    # step_size_up: 500
    # step_size_down: 500
    # cycle_momentum: false
  # path_loss_schedulers:
  #   weight:
  #     value: 1.0
  #     name: cosine
  #     start_factor: 1000.0
  #     end_factor: 0.0
  #     total_iters: 1000
  #   variance:
  #     value: 1.0
  #     name: cosine
  #     start_factor: 1.5
  #     end_factor: 0.0
  #     total_iters: 1000
  # TS_time_loss_names: F_mag
  # TS_time_loss_scales: 0.1
  # TS_time_loss_scheduler:
  #   F_mag:
  #     name: cosine
  #     start_factor: 0.0
  #     end_factor: 1.0
  #     total_iters: 1000
num_optimizer_iterations: 1000
output_dir: output
