inv_gauss:
    cos_cos :
        weight:
            value: 1.0
            name: cosine
            start_value: 1000.0
            end_value: 0.0
            last_step: 101
        variance:
            value: 1.0
            name: cosine
            start_value: 4.0
            end_value: 0.1
            last_step: 101


inv_poly:
    cos_cos :
        weight:
            value: 1.0
            name: cosine
            start_value: 1000.0
            end_value: 0.0
            last_step: 101
        order:
            value: 1.0
            name: cosine
            start_value: 0.10
            end_value: 10.0
            last_step: 101
 


inv_sine-gauss:
    cos_cos :
        weight:
            value: 1.0
            name: cosine
            start_value: 1000.0
            end_value: 0.0
            last_step: 101
        variance:
            value: 1.0
            name: cosine
            start_value: 0.50
            end_value: 0.1
            last_step: 101
    cos_lin :
        weight:
            value: 1.0
            name: cosine
            start_value: 1000.0
            end_value: 0.0
            last_step: 101
        variance:
            value: 1.0
            name: linear
            start_value: 5.0
            end_value: 0.1
            last_step: 101

inv_sine:
    cos :
        weight:
            value: 1.0
            name: cosine
            start_value: 1000.0
            end_value: 0.0
            last_step: 101
    lin :
        weight:
            value: 1.0
            name: linear
            start_value: 1.0
            end_value: 0.0
            last_step: 101