images: [[1.133, -1.486], [-1.166, 1.477]]

potential_params:
    potential: wolfe_schlegel

path_params:
    name: mlp
    n_embed : 8
    depth : 4

integrator_params:
    method : dopri5
    rtol : 1.0e-5
    atol : 1.0e-5
    computation : parallel
    sample_type : uniform
    path_loss_names: ['E_pvre', 'F_mag']
    path_loss_scales: [1.0, 0.1]

optimizer_params:
    name: adam
    lr : 1.0e-3 
    TS_region_loss_names: ['E']
    TS_region_loss_scales: [1.0]
    TS_time_loss_names: ['F_mag']
    TS_time_loss_scales: [1.0]

device: cpu

num_optimizer_iterations: 100